# Generated by Django 6.0.3 on 2026-03-06 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la asignatura')),
                ('horas_semanales', models.PositiveSmallIntegerField(default=2, verbose_name='Horas semanales')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='cursos.curso', verbose_name='Curso')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas', to='profesores.profesor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['curso', 'nombre'],
                'unique_together': {('nombre', 'curso')},
            },
        ),
    ]
