# Generated by Django 6.0.3 on 2026-03-08 19:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('destino', models.CharField(choices=[('todos_apoderados', 'Todos los apoderados'), ('todos_profesores', 'Todos los profesores'), ('todos', 'Apoderados y profesores'), ('curso_apoderados', 'Apoderados de un curso')], max_length=30)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_enviados', models.PositiveIntegerField(default=0)),
                ('enviado_email', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(blank=True, help_text='Solo si destino es apoderados de un curso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.curso')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_masivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envío Masivo',
                'verbose_name_plural': 'Envíos Masivos',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('mensaje', 'Mensaje libre'), ('masivo', 'Envío masivo')], default='mensaje', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('enviada_por_email', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('envio_masivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='notificaciones.enviomasivo')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
