# Generated by Django 6.0.3 on 2026-03-06 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('asignaturas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('positiva', 'Positiva'), ('negativa', 'Negativa'), ('neutral', 'Neutral / Informativa')], max_length=10, verbose_name='Tipo')),
                ('categoria', models.CharField(blank=True, max_length=20, verbose_name='Categoría')),
                ('descripcion', models.TextField(help_text='Describe el comportamiento o situación observada', verbose_name='Descripción')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('firmado_por_apoderado', models.BooleanField(default=False, verbose_name='Firmado por apoderado')),
                ('fecha_firma', models.DateField(blank=True, null=True, verbose_name='Fecha de firma')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='alumnos.alumno', verbose_name='Alumno')),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotaciones', to='asignaturas.asignatura', verbose_name='Asignatura (opcional)')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Anotación',
                'verbose_name_plural': 'Anotaciones',
                'ordering': ['-fecha', 'alumno__usuario__last_name'],
            },
        ),
    ]
