# Generated by Django 6.0.3 on 2026-03-06 17:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('asignaturas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('porcentaje_ponderacion', models.DecimalField(decimal_places=2, default=100.0, help_text='Ponderación en % para el promedio (ej: 60.00 para 60%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Tipo de Evaluación',
                'verbose_name_plural': 'Tipos de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0, message='La nota mínima es 1.0'), django.core.validators.MaxValueValidator(7.0, message='La nota máxima es 7.0')], verbose_name='Nota')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de evaluación')),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Prueba Unidad 3, Trabajo grupal...', max_length=200, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='alumnos.alumno', verbose_name='Alumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='asignaturas.asignatura', verbose_name='Asignatura')),
                ('ingresado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_ingresadas', to=settings.AUTH_USER_MODEL, verbose_name='Ingresado por')),
                ('tipo_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='notas.tipoevaluacion', verbose_name='Tipo de evaluación')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['alumno', 'asignatura', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='PromedioAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('cantidad_notas', models.PositiveSmallIntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios', to='alumnos.alumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios', to='asignaturas.asignatura')),
            ],
            options={
                'verbose_name': 'Promedio por Asignatura',
                'verbose_name_plural': 'Promedios por Asignatura',
                'unique_together': {('alumno', 'asignatura')},
            },
        ),
    ]
