# Generated by Django 6.0.3 on 2026-04-24 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_curso'),
        ('asignaturas', '0001_initial'),
        ('notas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('alumno', 'asignatura', 'tipo_evaluacion', 'fecha', 'descripcion'), name='unique_nota_por_evaluacion'),
        ),
    ]
