# Generated by Django 6.0.3 on 2026-03-06 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesores', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEducacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('basica', 'Educación Básica'), ('media', 'Educación Media')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Nivel Educacional',
                'verbose_name_plural': 'Niveles Educacionales',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.PositiveSmallIntegerField(help_text='1-8 para básica, 1-4 para media', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Grado')),
                ('letra', models.CharField(help_text='Ej: A, B, C', max_length=1, verbose_name='Letra')),
                ('anio_academico', models.PositiveSmallIntegerField(help_text='Ej: 2024', verbose_name='Año académico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('profesor_jefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_como_jefe', to='profesores.profesor', verbose_name='Profesor jefe')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='cursos.niveleducacional', verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['anio_academico', 'nivel', 'grado', 'letra'],
                'unique_together': {('nivel', 'grado', 'letra', 'anio_academico')},
            },
        ),
    ]
