# Generated by Django 6.0.3 on 2026-04-24 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_curso'),
        ('asignaturas', '0001_initial'),
        ('asistencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['alumno', 'fecha'], name='asistencia__alumno__f921fb_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['fecha'], name='asistencia__fecha_04aaa4_idx'),
        ),
    ]
