# Generated by Django 6.0.3 on 2026-03-08 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('trimestre', 'Trimestre'), ('semestre', 'Semestre')], max_length=10, verbose_name='Tipo')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('anio', models.PositiveSmallIntegerField(default=2026, verbose_name='Año')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de término')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['-anio', 'tipo', 'numero'],
                'unique_together': {('tipo', 'numero', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='ComentarioInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario del profesor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_informe', to='alumnos.alumno')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_emitidos', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='informes.periodo')),
            ],
            options={
                'verbose_name': 'Comentario de Informe',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('alumno', 'periodo')},
            },
        ),
    ]
