# Generated by Django 6.0.3 on 2026-05-01 14:46

from django.db import migrations, models

import usuarios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, help_text='Formato: 12345678-9', max_length=12, null=True, unique=True, validators=[usuarios.validators.validar_rut], verbose_name='RUT'),
        ),
    ]
