# Generated by Django 6.0.3 on 2026-03-13 02:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('nota', 'Nota'), ('anotacion', 'Anotación')], max_length=20, verbose_name='Módulo')),
                ('objeto_id', models.PositiveIntegerField(verbose_name='ID del registro modificado')),
                ('accion', models.CharField(choices=[('edicion', 'Edición'), ('eliminacion', 'Eliminación')], default='edicion', max_length=20, verbose_name='Acción')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('descripcion_objeto', models.CharField(blank=True, max_length=200, verbose_name='Objeto afectado')),
                ('datos_antes', models.JSONField(verbose_name='Estado anterior')),
                ('datos_despues', models.JSONField(blank=True, null=True, verbose_name='Estado posterior')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cambios', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha'],
            },
        ),
    ]
