# Generated by Django 6.0.3 on 2026-05-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcambio',
            name='accion',
            field=models.CharField(choices=[('edicion', 'Edición'), ('eliminacion', 'Eliminación'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('login_fallido', 'Intento fallido'), ('cambio_contrasena', 'Cambio de contraseña'), ('cambio_rol', 'Cambio de rol'), ('desactivacion', 'Desactivación')], default='edicion', max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='modelo',
            field=models.CharField(choices=[('nota', 'Nota'), ('anotacion', 'Anotación'), ('usuario', 'Usuario')], max_length=20, verbose_name='Módulo'),
        ),
    ]
